name: master_class
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^4.0.0
  firebase_storage: ^11.2.2 
  firebase_storage_web: ^3.6.2
  http: ^0.13.0
  google_sign_in: ^6.1.3
  cached_network_image: ^3.2.3
  flutter_zoom_drawer: ^3.0.4+1
  url_launcher: ^6.1.11
  logger: ^1.4.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/DB/papers/

fonts:
- family: AppIcons
  fonts:
    - asset: assets/icons/AppIcons.ttf

